Repository claroline/Distribution, pull requests merged in 2018-11, with the labels that each got.

#5106 [CoreBundle] multi search for data lists
  main/app/Entity/Parameters/ListParameters.php
  main/app/Resources/modules/content/list/components/header.jsx
  main/app/Resources/modules/content/list/containers/data.jsx
  main/app/Resources/modules/content/list/parameters/components/form.jsx
  main/app/Resources/modules/content/list/parameters/prop-types.js
  main/app/Resources/modules/content/list/prop-types.js
  main/app/Resources/modules/content/list/store/actions.js
  main/app/Resources/modules/content/list/store/connect.js
  main/app/Resources/modules/content/list/store/reducer.js
  main/app/Resources/modules/content/list/store/selectors.js
  main/app/Resources/modules/content/pagination/prop-types.js
  main/app/Resources/modules/content/pagination/store/actions.js
  main/app/Resources/modules/content/pagination/store/index.js
  main/app/Resources/modules/content/pagination/store/reducer.js
  main/app/Resources/modules/content/pagination/store/selectors.js
  main/app/Resources/modules/content/search/components/full.jsx
  main/app/Resources/modules/content/search/components/prop.jsx
  main/app/Resources/modules/content/search/components/search.jsx
  main/app/Resources/modules/content/search/components/unified.jsx
  main/app/Resources/modules/content/search/constants.js
  main/app/Resources/modules/content/search/containers/full.jsx
  main/app/Resources/modules/content/search/containers/search.jsx
  main/app/Resources/modules/content/search/containers/unified.jsx
  main/app/Resources/modules/content/search/prop-types.js
  main/app/Resources/modules/content/search/store/actions.js
  main/app/Resources/modules/content/search/store/connect.js
  main/app/Resources/modules/content/search/store/index.js
  main/app/Resources/modules/content/search/store/reducer.js
  main/app/Resources/modules/content/search/store/selectors.js
  main/app/Resources/modules/data/boolean/components/filter.jsx
  main/app/Resources/modules/data/choice/components/search.jsx
  main/app/Resources/modules/data/choice/index.js
  main/app/Resources/modules/data/date/components/search.jsx
  main/app/Resources/modules/data/prop-types.js
  main/app/Resources/translations/actions.en.json
  main/app/Resources/translations/actions.fr.json
  main/core/API/Serializer/Resource/Types/DirectorySerializer.php
  main/core/API/Serializer/Widget/Type/ListWidgetSerializer.php
  main/core/Migrations/pdo_mysql/Version20181105104402.php
  main/core/Resources/less/data/boolean.less
  main/core/Resources/less/layout/components/index.less
  main/core/Resources/less/layout/components/search.less
  main/core/Resources/less/layout/list/data-lists.less
  main/core/Resources/modules/administration/workspace/workspace/components/workspaces.jsx
  main/core/Resources/modules/data/types/resource/components/filter.jsx
  main/core/Resources/modules/layout/logs/reducer.js
  main/core/Resources/modules/resource/explorer/components/current.jsx
  main/core/Resources/modules/widget/types/list/components/widget.jsx
  main/core/Resources/modules/widget/types/list/containers/widget.jsx
  main/core/Resources/modules/widget/types/list/store/selectors.js
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  plugin/announcement/Resources/modules/resources/announcement/store/reducer.js
  plugin/blog/Resources/modules/resources/blog/store/reducer.js
Labels: in progress

#5124 [ClacoForm] Fixes clacoform for anonymous
  plugin/claco-form/Finder/EntryFinder.php
  plugin/claco-form/Resources/modules/resources/claco-form/containers/resource.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/store/selectors.js
Labels: clacoForm

#5168 [ClacoForm] Adds a command to import entries from a CSV
  main/core/Command/Import/CreateWorkspaceFromCsvCommand.php
  plugin/claco-form/Command/CreateEntriesFromCsvCommand.php
  plugin/claco-form/Manager/ClacoFormManager.php
Labels: clacoForm

#5173 [ClacoForm] Updates import command
  plugin/claco-form/Command/CreateEntriesFromCsvCommand.php
  plugin/claco-form/Manager/ClacoFormManager.php
Labels: clacoForm

#5223 Updates scheduled tasks & planned notifications
  main/core/Resources/modules/administration/scheduled-task/actions.js
  main/core/Resources/modules/administration/scheduled-task/components/scheduled-task.jsx
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  plugin/planned-notification/Controller/API/PlannedNotificationController.php
  plugin/planned-notification/Controller/PlannedNotificationToolController.php
  plugin/planned-notification/Finder/PlannedNotificationFinder.php
  plugin/planned-notification/Listener/PlannedNotificationListener.php
  plugin/planned-notification/Manager/PlannedNotificationManager.php
  plugin/planned-notification/Resources/config/routing.yml
  plugin/planned-notification/Resources/modules/data/message/components/message-form-group.jsx
  plugin/planned-notification/Resources/modules/data/roles/components/roles-form-group.jsx
  plugin/planned-notification/Resources/modules/data/types/notifications/components/display.jsx
  plugin/planned-notification/Resources/modules/data/types/notifications/components/group.jsx
  plugin/planned-notification/Resources/modules/data/types/notifications/components/input.jsx
  plugin/planned-notification/Resources/modules/data/types/notifications/index.js
  plugin/planned-notification/Resources/modules/modals/notifications/components/modal.jsx
  plugin/planned-notification/Resources/modules/modals/notifications/containers/modal.jsx
  plugin/planned-notification/Resources/modules/modals/notifications/index.js
  plugin/planned-notification/Resources/modules/modals/notifications/store/index.js
  plugin/planned-notification/Resources/modules/modals/notifications/store/reducer.js
  plugin/planned-notification/Resources/modules/modals/notifications/store/selectors.js
  plugin/planned-notification/Resources/modules/plugin.js
  plugin/planned-notification/Resources/modules/tools/planned-notification/message/components/message.jsx
  plugin/planned-notification/Resources/modules/tools/planned-notification/notification/components/manual-notification.jsx
  plugin/planned-notification/Resources/modules/tools/planned-notification/notification/components/notification-list.jsx
  plugin/planned-notification/Resources/modules/tools/planned-notification/notification/components/notification-tab.jsx
  plugin/planned-notification/Resources/modules/tools/planned-notification/notification/components/notification.jsx
  plugin/planned-notification/Resources/modules/tools/planned-notification/notification/components/notifications.jsx
  plugin/planned-notification/Resources/modules/tools/planned-notification/notification/data/components/notification-card.jsx
  plugin/planned-notification/Resources/modules/tools/planned-notification/notification/reducer.js
  plugin/planned-notification/Resources/translations/planned_notification.en.json
  plugin/planned-notification/Resources/translations/planned_notification.fr.json
  plugin/planned-notification/Serializer/PlannedNotificationSerializer.php
Labels: in progress

#5232 adds a new plugin Slideshow
  composer.json
  main/app/Resources/modules/page/components/simple.jsx
  main/core/Resources/less/layout/pages.less
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  plugin/path/Entity/Path/Path.php
  plugin/path/Listener/Resource/PathListener.php
  plugin/path/Resources/modules/resources/path/editor/components/parameters-form.jsx
  plugin/path/Resources/translations/path.en.json
  plugin/path/Resources/translations/path.fr.json
  plugin/path/Serializer/PathSerializer.php
  plugin/slideshow/ClarolineSlideshowBundle.php
  plugin/slideshow/Controller/SlideshowController.php
  plugin/slideshow/Entity/Resource/Slide.php
  plugin/slideshow/Entity/Resource/Slideshow.php
  plugin/slideshow/Listener/Resource/SlideshowListener.php
  plugin/slideshow/Migrations/pdo_mysql/Version20181129112146.php
  plugin/slideshow/Resources/config/config.yml
  plugin/slideshow/Resources/config/routing.yml
  plugin/slideshow/Resources/modules/plugin.js
  plugin/slideshow/Resources/modules/resources/slideshow/components/resource.jsx
  plugin/slideshow/Resources/modules/resources/slideshow/components/slides.jsx
  plugin/slideshow/Resources/modules/resources/slideshow/containers/resource.jsx
  plugin/slideshow/Resources/modules/resources/slideshow/editor/components/editor.jsx
  plugin/slideshow/Resources/modules/resources/slideshow/editor/modals/slide/components/modal.jsx
  plugin/slideshow/Resources/modules/resources/slideshow/editor/modals/slide/containers/modal.jsx
  plugin/slideshow/Resources/modules/resources/slideshow/editor/modals/slide/index.js
  plugin/slideshow/Resources/modules/resources/slideshow/editor/modals/slide/store/index.js
  plugin/slideshow/Resources/modules/resources/slideshow/editor/modals/slide/store/reducer.js
  plugin/slideshow/Resources/modules/resources/slideshow/editor/modals/slide/store/selectors.js
  plugin/slideshow/Resources/modules/resources/slideshow/editor/store/index.js
  plugin/slideshow/Resources/modules/resources/slideshow/editor/store/reducer.js
  plugin/slideshow/Resources/modules/resources/slideshow/editor/store/selectors.js
  plugin/slideshow/Resources/modules/resources/slideshow/index.js
  plugin/slideshow/Resources/modules/resources/slideshow/player/components/overview.jsx
  plugin/slideshow/Resources/modules/resources/slideshow/player/components/player.jsx
  plugin/slideshow/Resources/modules/resources/slideshow/player/store/index.js
  plugin/slideshow/Resources/modules/resources/slideshow/player/store/selectors.js
  plugin/slideshow/Resources/modules/resources/slideshow/prop-types.js
  plugin/slideshow/Resources/modules/resources/slideshow/store/actions.js
  plugin/slideshow/Resources/modules/resources/slideshow/store/index.js
  plugin/slideshow/Resources/modules/resources/slideshow/store/reducer.js
  plugin/slideshow/Resources/modules/resources/slideshow/store/selectors.js
  plugin/slideshow/Resources/schemas/slideshow.json
  plugin/slideshow/Resources/styles/mixins.less
  plugin/slideshow/Resources/styles/resources/slideshow.less
  plugin/slideshow/Resources/styles/variables.less
  plugin/slideshow/Resources/translations/actions.en.json
  plugin/slideshow/Resources/translations/actions.fr.json
  plugin/slideshow/Resources/translations/resource.en.json
  plugin/slideshow/Resources/translations/resource.fr.json
  plugin/slideshow/Resources/translations/slideshow.en.json
  plugin/slideshow/Resources/translations/slideshow.fr.json
  plugin/slideshow/Serializer/SlideshowSerializer.php
  plugin/slideshow/assets.json
Labels: in progress

#5248 [ExoBundle] Correction updates
  plugin/exo/Repository/PaperRepository.php
  plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
  plugin/exo/Resources/modules/resources/quiz/components/resource.jsx
  plugin/exo/Resources/modules/resources/quiz/containers/resource.jsx
Labels: ExoBundle
