Repository claroline/Distribution, pull requests merged in 2018-10, with the labels that each got.

#4892 Elorfin fixes
  main/app/Resources/modules/overlay/header/components/title.jsx
  main/app/Resources/modules/overlay/header/components/user.jsx
  main/core/Resources/less/layout/header.less
  main/core/Resources/less/layout/list/data-lists.less
  main/core/Resources/less/users/index.less
  main/core/Resources/less/widget/index.less
  main/core/Resources/modules/data/components/data-card.jsx
  main/core/Resources/modules/resources/directory/player/components/directory.jsx
Labels: no-squash

#4928 [TeamBundle] Allows to self register/unregister from teams list
  plugin/team/Resources/modules/tools/team/components/team.jsx
  plugin/team/Resources/modules/tools/team/components/teams.jsx
  plugin/team/Resources/modules/tools/team/store/actions.js
Labels: TeamBundle

#4936 Updates time tracking
  main/core/Event/Log/LogGenericEvent.php
  main/core/Event/Log/LogResourceReadEvent.php
  main/core/Event/Log/LogWorkspaceToolReadEvent.php
  main/core/Listener/Log/LogListener.php
  main/core/Manager/LogConnectManager.php
Labels: in progress, needs-changes

#4964 [CoreBundle] enhances widget styles configuration
  main/core/API/Serializer/Widget/HomeTabSerializer.php
  main/core/API/Serializer/Widget/WidgetContainerSerializer.php
  main/core/Entity/Tab/HomeTabConfig.php
  main/core/Entity/Widget/WidgetContainerConfig.php
  main/core/Entity/Widget/WidgetInstanceConfig.php
  main/core/Library/Installation/AdditionalInstaller.php
  main/core/Migrations/pdo_mysql/Version20181010072637.php
  main/core/Migrations/pdo_mysql/Version20181010092915.php
  main/core/Resources/less/themes/default/variables.less
  main/core/Resources/less/widget/index.less
  main/core/Resources/modules/layout/components/heading.jsx
  main/core/Resources/modules/layout/form/components/field/color-picker.jsx
  main/core/Resources/modules/tools/home/components/tabs.jsx
  main/core/Resources/modules/tools/home/editor/components/tab.jsx
  main/core/Resources/modules/tools/home/store/selectors.js
  main/core/Resources/modules/widget/editor/components/form.jsx
  main/core/Resources/modules/widget/editor/components/widget.jsx
  main/core/Resources/modules/widget/player/components/widget.jsx
  main/core/Resources/modules/widget/prop-types.js
  main/core/Resources/modules/widget/utils.js
  main/core/Resources/styles/tools/home.less
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  main/core/Security/Voter/ResourceVoter.php
Labels: new migrations, no-squash

#4969 [BlogBundle] Fixes selectors call in editor
  plugin/blog/Resources/modules/resources/blog/editor/components/blog-options.jsx
Labels: BlogBundle

#4989 [CursusBundle] Doesn't filter by organizations for admin
  plugin/cursus/Controller/APINew/CourseController.php
  plugin/cursus/Controller/APINew/CursusController.php
  plugin/cursus/Controller/APINew/SessionController.php
  plugin/cursus/Controller/APINew/SessionEventController.php
  plugin/cursus/Finder/CourseFinder.php
  plugin/cursus/Finder/CursusFinder.php
  plugin/cursus/Finder/SessionEventFinder.php
  plugin/cursus/Finder/SessionFinder.php
Labels: CursusBundle

#5006 Fixes root chapter copy of lesson
  plugin/lesson/Listener/Resource/LessonListener.php
  plugin/lesson/Manager/ChapterManager.php
Labels: LessonBundle

#5013 Fixes agenda
  plugin/agenda/Listener/AgendaListener.php
Labels: AgendaBundle

#5019 Fixes routing in messaging
  plugin/message/Resources/modules/tools/messaging/components/messages.jsx
Labels: MessageBundle

#5022 Adds action to open a survey
  plugin/survey/Controller/SurveyController.php
  plugin/survey/Resources/config/config.yml
  plugin/survey/Resources/modules/plugin.js
  plugin/survey/Resources/modules/resources/survey/actions/open.js
  plugin/survey/Resources/views/survey/question_create_form.html.twig
  plugin/survey/Resources/views/survey/question_edit_form.html.twig
  plugin/survey/Resources/views/survey/question_title_create_form.html.twig
  plugin/survey/Resources/views/survey/question_title_edit_form.html.twig
  plugin/survey/Resources/views/survey/survey_parameters_edit_form.html.twig
Labels: SurveyBundle

#5040 Fix resources
  main/core/Manager/Resource/ResourceRestrictionsManager.php
  main/core/Resources/modules/resource/store/actions.js
  main/core/Resources/modules/resource/store/reducer.js
  main/core/Security/Voter/WorkspaceVoter.php
Labels: no-squash

#5062 [CoreBundle] multiple fixes on resources
  main/app/Resources/modules/content/card/components/data.jsx
  main/app/Resources/modules/content/card/prop-types.js
  main/app/Resources/modules/content/list/components/view/data-grid.jsx
  main/app/Resources/modules/content/list/store/actions.js
  main/app/Resources/modules/content/list/store/connect.js
  main/core/Listener/Resource/ResourceListener.php
  main/core/Resources/modules/resource/explorer/store/actions.js
  main/core/Resources/modules/resource/explorer/store/reducer.js
  main/core/Resources/modules/resource/index.js
  main/core/Resources/modules/resource/store/actions.js
  main/core/Resources/modules/resources/directory/player/store/reducer.js
  main/core/Resources/modules/tool/constants.js
  main/core/Resources/modules/tool/store/actions.js
  main/core/Resources/modules/tool/store/index.js
  main/core/Resources/modules/tool/store/reducer.js
  main/core/Resources/modules/widget/content/components/form.jsx
Labels: no-squash

#5065 [ForumBundle] Multiple fixes for Forum
  main/core/Resources/modules/user/message/components/user-message-form.jsx
  plugin/forum/Controller/API/ForumController.php
  plugin/forum/Controller/API/SubjectController.php
  plugin/forum/Finder/MessageFinder.php
  plugin/forum/Finder/SubjectFinder.php
  plugin/forum/Listener/Resource/ForumListener.php
  plugin/forum/Manager/Manager.php
  plugin/forum/Resources/modules/resources/forum/moderation/components/blocked-subjects.jsx
  plugin/forum/Resources/modules/resources/forum/player/components/message-comments.jsx
  plugin/forum/Resources/modules/resources/forum/player/components/subject-form.jsx
  plugin/forum/Resources/modules/resources/forum/player/components/subject.jsx
  plugin/forum/Resources/modules/resources/forum/player/components/subjects.jsx
  plugin/forum/Resources/modules/resources/forum/store/actions.js
  plugin/forum/Resources/modules/resources/forum/store/reducer.js
  plugin/forum/Resources/modules/resources/forum/store/selectors.js
  plugin/forum/Resources/translations/forum.en.json
  plugin/forum/Resources/translations/forum.fr.json
  plugin/forum/Serializer/SubjectSerializer.php
Labels: ForumBundle

#5099 [SurveyBundle] Removes misplaced function
  plugin/survey/Controller/SurveyController.php
Labels: SurveyBundle
