Repository claroline/Distribution, pull requests merged in 2018-07, with the labels that each got.

#4383 [Scorm] Fixes scorm deletion + updates conversion
  plugin/scorm/Command/DeleteOldScormCommand.php
  plugin/scorm/Listener/Scorm12Listener.php
  plugin/scorm/Listener/Scorm2004Listener.php
  plugin/scorm/Listener/ScormListener.php
  plugin/scorm/Manager/ScormManager.php
Labels: ScormBundle

#4376 [LessonBundle] Lesson react refactoring fixes
  plugin/lesson/Controller/API/ChapterController.php
  plugin/lesson/Manager/ChapterManager.php
  plugin/lesson/Resources/modules/resources/lesson/components/chapter-form.jsx
  plugin/lesson/Resources/modules/resources/lesson/components/tree/utils.js
  plugin/lesson/Resources/modules/resources/lesson/player/components/player.jsx
  plugin/lesson/Resources/modules/resources/lesson/store/actions.js
  plugin/lesson/Resources/modules/resources/lesson/store/reducer.js
Labels: LessonBundle

#4400 Updates resources picker in path editor
  main/core/API/Serializer/Resource/ResourceNodeSerializer.php
  main/core/Controller/APINew/Resource/ResourceNodeController.php
  main/core/Controller/APINew/ResourceNodeController.php
  main/core/Resources/modules/resource/explorer/components/explorer.jsx
  main/core/Resources/modules/resource/explorer/store/selectors.js
  main/core/Resources/modules/resource/modals/explorer/components/explorer.jsx
  main/core/Resources/modules/resource/store/selectors.js
  plugin/path/Resources/modules/resources/path/editor/components/editor.jsx
Labels: CoreBundle, PathBundle

#4407 [Lesson Bundle] Lesson react refactoring enhancement
  plugin/lesson/Resources/modules/resources/lesson/components/chapter.jsx
  plugin/lesson/Resources/styles/resources/lesson.less
Labels: LessonBundle

#4414 Checks existence of resource type before disabling it
  plugin/dropzone/Library/Installation/Updater/Updater120000.php
  plugin/scorm/Library/Installation/Updater/Updater120000.php
Labels: EvaluationBundle, ScormBundle

#4418 Resources copy/move
  main/core/API/Serializer/Resource/ResourceNodeSerializer.php
  main/core/Entity/Resource/ResourceNode.php
  main/core/Listener/Resource/ResourceListener.php
  main/core/Resources/modules/plugin.js
  main/core/Resources/modules/resource/actions/copy.js
  main/core/Resources/modules/resource/actions/move.js
  main/core/Resources/modules/resource/actions/publish.js
  main/core/Resources/modules/resource/actions/rights.js
  main/core/Resources/modules/resource/actions/unpublish.js
  main/core/Resources/modules/resource/explorer/components/explorer.jsx
  main/core/Resources/modules/resource/explorer/containers/explorer.jsx
  main/core/Resources/modules/resource/explorer/store/actions.js
  main/core/Resources/modules/resource/modals/explorer/components/explorer.jsx
  main/core/Resources/modules/resource/utils.js
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  plugin/path/Resources/modules/resources/path/editor/components/editor.jsx
  plugin/path/Resources/modules/resources/path/editor/reducer.js
  plugin/path/Resources/modules/resources/path/reducer.js
  plugin/scorm/Listener/ScormListener.php
  plugin/scorm/Repository/ScormRepository.php
  plugin/social-media/Resources/modules/resource/actions/like.js
  plugin/social-media/Resources/modules/resource/actions/unlike.js
Labels: CoreBundle

#4450 [CoreBundle] manages home tabs position
  main/core/Resources/modules/tools/home/editor/actions.js
  main/core/Resources/modules/tools/home/editor/components/editor.jsx
  main/core/Resources/modules/tools/home/editor/components/tab.jsx
  main/core/Resources/modules/tools/home/editor/reducer.js
Labels: needs-changes

#4468 Fixes resources deletion
  main/core/Listener/Resource/ResourceListener.php
  main/core/Resources/modules/resource/actions/delete.js
  main/core/Resources/translations/platform.de.json
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.es.json
  main/core/Resources/translations/platform.fr.json
  plugin/link/Listener/Resource/ResourceListener.php
  plugin/link/Manager/ShortcutManager.php
  plugin/scorm/Listener/ScormListener.php
Labels: CoreBundle

#4472 [PdfPlayerBundle] Pdf player react
  plugin/pdf-player/DependencyInjection/ClarolinePdfPlayerExtension.php
  plugin/pdf-player/Listener/PdfPlayerListener.php
  plugin/pdf-player/Resources/modules/pdf/Controller/PdfController.js
  plugin/pdf-player/Resources/modules/pdf/Directive/ViewPdfDirective.js
  plugin/pdf-player/Resources/modules/pdf/Partial/view_pdf.html
  plugin/pdf-player/Resources/modules/pdf/module.js
  plugin/pdf-player/Resources/modules/plugin.js
  plugin/pdf-player/Resources/modules/resources/pdf/bootstrap.js
  plugin/pdf-player/Resources/modules/resources/pdf/components/resource.jsx
  plugin/pdf-player/Resources/modules/resources/pdf/index.js
  plugin/pdf-player/Resources/modules/resources/pdf/player/components/player.jsx
  plugin/pdf-player/Resources/modules/resources/pdf/reducer.js
  plugin/pdf-player/Resources/modules/resources/pdf/selectors.js
  plugin/pdf-player/Resources/views/open.html.twig
  plugin/pdf-player/Resources/views/pdf.html.twig
  plugin/pdf-player/assets.json
Labels: pdfPlayer

#4479 [CoreBundle] fixes WorkspaceVoter when using view as
  main/core/Security/Voter/WorkspaceVoter.php
Labels: no-squash

#4489 Move widget
  main/core/API/Serializer/Widget/HomeTabSerializer.php
  main/core/API/Serializer/Widget/WidgetContainerSerializer.php
  main/core/Controller/Administration/DesktopConfigurationController.php
  main/core/Entity/Widget/WidgetContainer.php
  main/core/Listener/Administration/AdministrationToolListener.php
  main/core/Listener/Administration/HomeListener.php
  main/core/Migrations/pdo_mysql/Version20180730184500.php
  main/core/Resources/less/widgets/index.less
  main/core/Resources/modules/administration/home/index.js
  main/core/Resources/modules/widget/content/modals/parameters/components/parameters.jsx
  main/core/Resources/modules/widget/editor/components/grid.jsx
  main/core/Resources/modules/widget/editor/components/widget.jsx
  main/core/Resources/translations/widget.fr.json
  main/core/Resources/views/administration/home.html.twig
  main/core/assets.json
Labels: needs-changes
