Repository claroline/Distribution, pull requests merged in 2018-02, with the labels that each got.

#3542 merge 10.x
  changelogs/10.x-10.10.x.md
  main/core/API/Crud/User/OrganizationCrud.php
  main/core/API/Serializer/ParametersSerializer.php
  main/core/API/Serializer/Translatable/TranslatableSerializer.php
  main/core/API/Serializer/User/GroupSerializer.php
  main/core/API/SerializerProvider.php
  main/core/Controller/APINew/AbstractCrudController.php
  main/core/Controller/Administration/ParametersController.php
  main/core/Entity/Content.php
  main/core/Entity/Facet/FieldFacetChoice.php
  main/core/Entity/User.php
  main/core/Library/Logo/LogoService.php
  main/core/Library/Utilities/FileUtilities.php
  main/core/Repository/UserRepository.php
  main/core/Resources/config/suggested/security_prod.yml
  main/core/Resources/modules/administration/user/parameters/components/parameters-tab.jsx
  main/core/Resources/modules/administration/workspace/workspace/components/workspace-list.jsx
  main/core/Resources/modules/administration/workspace/workspace/components/workspaces.jsx
  main/core/Resources/modules/data/index.js
  main/core/Resources/modules/data/types/translated/index.js
  main/core/Resources/modules/layout/form/components/group/text-group.jsx
  main/core/Resources/modules/layout/form/components/group/translated-group.jsx
  main/core/Resources/modules/user/tracking/components/timeline.jsx
  main/core/Resources/modules/utilities/app/bootstrap.js
  main/core/Resources/public/js/administration/logos.js
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  plugin/bibliography/API/Serializer/BookReferenceSerializer.php
  plugin/external-user-group-synchronization/Manager/ExternalSynchronizationManager.php
  plugin/external-user-group-synchronization/Manager/ExternalSynchronizationUserManager.php
Labels: no-squash

#3564 [CoreBundle] Regular expression fix
  main/core/Library/Utilities/ClaroUtilities.php
Labels: CoreBundle

#3589 [BlogBundle] Fix permission check in blog API
  plugin/blog/Controller/API/ApiController.php
  plugin/blog/Manager/PostManager.php
  plugin/blog/Repository/PostRepository.php
Labels: BlogBundle

#3595 [CursusBundle] Hides finished session events in widget
  plugin/cursus/Resources/views/Widget/coursesListForRegistrationWidget.html.twig
  plugin/cursus/Resources/views/Widget/coursesRegistrationWidget.html.twig
Labels: CursusBundle
