Repository claroline/Distribution, pull requests merged in 2018-03, with the labels that each got.

#3684 [CoreBundle] Exposes current user in JS as JSON object
  main/core/Resources/modules/user/current.js
Labels: needs-approval

#3682 Only notify for comments users who have a configured role
  plugin/claco-form/Entity/ClacoFormWidgetConfig.php
  plugin/claco-form/Manager/ClacoFormManager.php
Labels: clacoForm

#3708 [NEW MIGRATIONS] Allow to disable resources deletion
  main/core/Controller/APINew/WorkspaceController.php
  main/core/Controller/ResourceController.php
  main/core/Controller/WorkspaceController.php
  main/core/Entity/Resource/ResourceNode.php
  main/core/Form/ResourcePropertiesType.php
  main/core/Manager/ResourceManager.php
  main/core/Migrations/pdo_mysql/Version20180306165800.php
  main/core/Repository/ResourceQueryBuilder.php
  main/core/Resources/modules/administration/workspace/workspace/actions.js
  main/core/Resources/modules/administration/workspace/workspace/components/workspaces.jsx
  main/core/Resources/modules/layout/alert/actions.js
  main/core/Resources/modules/layout/alert/constants.js
  main/core/Resources/public/js/resource/manager/views/resource/actions.js
  main/core/Resources/public/js/resource/manager/views/resource/nodes.js
  main/core/Resources/public/js/tool/workspace/workspace_parameters_edit.js
  main/core/Resources/translations/alerts.en.json
  main/core/Resources/translations/alerts.fr.json
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  main/core/Resources/views/Resource/deleteConfirm.html.twigjs
  main/core/Resources/views/Resource/listElement.html.twigjs
  main/core/Resources/views/Resource/propertiesForm.html.twig
  main/core/Resources/views/Resource/thumbnail.html.twigjs
  main/core/Resources/views/Tool/workspace/parameters/workspaceEdit.html.twig
  plugin/exo/Entity/Attempt/Paper.php
  plugin/exo/Migrations/pdo_mysql/Version20180306143853.php
Labels: CoreBundle, ExoBundle

#3747 [ClacoForm] fix router
  plugin/claco-form/Resources/modules/resources/claco-form/components/resource.jsx
Labels: clacoForm

#3807 [CoreBundle] fixes workspace users tool
  main/app/Resources/translations/actions.en.json
  main/app/Resources/translations/actions.fr.json
  main/app/Resources/translations/data.en.json
  main/app/Resources/translations/data.fr.json
  main/core/API/Serializer/User/RoleSerializer.php
  main/core/API/Serializer/WorkspaceSerializer.php
  main/core/Controller/APINew/WorkspaceController.php
  main/core/Entity/Workspace/Workspace.php
  main/core/Resources/less/layout/modal/index.less
  main/core/Resources/modules/administration/user/group/components/group.jsx
  main/core/Resources/modules/administration/user/location/components/location.jsx
  main/core/Resources/modules/administration/user/organization/components/organization.jsx
  main/core/Resources/modules/administration/user/parameters/components/parameters-tab.jsx
  main/core/Resources/modules/administration/user/role/components/role-list.jsx
  main/core/Resources/modules/administration/user/role/components/role.jsx
  main/core/Resources/modules/administration/workspace/workspace/actions.js
  main/core/Resources/modules/administration/workspace/workspace/components/workspace.jsx
  main/core/Resources/modules/data/details/components/details.jsx
  main/core/Resources/modules/data/index.js
  main/core/Resources/modules/data/list/components/data-list.jsx
  main/core/Resources/modules/data/list/modals/containers/data-picker.jsx
  main/core/Resources/modules/data/types/image.js
  main/core/Resources/modules/data/types/url/index.js
  main/core/Resources/modules/layout/form/components/field/locale.jsx
  main/core/Resources/modules/layout/form/components/field/url.jsx
  main/core/Resources/modules/layout/form/components/group/locale-group.jsx
  main/core/Resources/modules/layout/form/components/group/translated-group.jsx
  main/core/Resources/modules/layout/form/components/group/url-group.jsx
  main/core/Resources/modules/layout/form/components/page-actions.jsx
  main/core/Resources/modules/layout/modal/components/base.jsx
  main/core/Resources/modules/layout/modal/components/confirm.jsx
  main/core/Resources/modules/layout/modal/components/generic-type-picker.jsx
  main/core/Resources/modules/layout/tabs/components/page.jsx
  main/core/Resources/modules/platform/config.js
  main/core/Resources/modules/scaffolding/asset/index.js
  main/core/Resources/modules/scaffolding/clipboard/index.js
  main/core/Resources/modules/workspace/prop-types.js
  main/core/Resources/modules/workspace/user/components/tool.jsx
  main/core/Resources/modules/workspace/user/group/components/group-tab.jsx
  main/core/Resources/modules/workspace/user/index.js
  main/core/Resources/modules/workspace/user/modals/index.js
  main/core/Resources/modules/workspace/user/modals/reducer.js
  main/core/Resources/modules/workspace/user/parameters/components/parameters-tab.jsx
  main/core/Resources/modules/workspace/user/pending/components/modal/confirm-registration.jsx
  main/core/Resources/modules/workspace/user/pending/components/pending-tab.jsx
  main/core/Resources/modules/workspace/user/pending/components/pendings.jsx
  main/core/Resources/modules/workspace/user/pending/reducer.js
  main/core/Resources/modules/workspace/user/reducer.js
  main/core/Resources/modules/workspace/user/role/components/role-list.jsx
  main/core/Resources/modules/workspace/user/role/components/role-tab.jsx
  main/core/Resources/modules/workspace/user/role/components/role.jsx
  main/core/Resources/modules/workspace/user/role/components/roles.jsx
  main/core/Resources/modules/workspace/user/role/modal.js
  main/core/Resources/modules/workspace/user/user/components/user-list.jsx
  main/core/Resources/modules/workspace/user/user/components/user-tab.jsx
  main/core/Resources/modules/workspace/user/user/components/users.jsx
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  main/core/Resources/views/Workspace/usersManagement.html.twig
Labels: in progress

#3818 [ClacoForm] Fixes filters for custom field
  plugin/claco-form/API/Finder/EntryFinder.php
  plugin/claco-form/Controller/ClacoFormController.php
Labels: in progress

#3820 [CoreBundle] Fix user search by mail and mailer (v10)
  main/core/API/Finder/User/UserFinder.php
  main/core/Library/Mailing/Mailer.php
Labels: CoreBundle

#3846 [CoreBundle] fixes FontAwesome path when using url rewriting
  main/core/Resources/less/main.less
Labels: bug, urgent
