Repository claroline/Distribution, pull requests merged in 2018-08, with the labels that each got.

#4502 [AnnouncementBundle] Fixes announcement sending form
  plugin/announcement/Resources/modules/resources/announcement/components/announce-post.jsx
  plugin/announcement/Resources/modules/resources/announcement/components/announce-send.jsx
  plugin/announcement/Resources/modules/resources/announcement/modals/index.js
  plugin/announcement/Resources/modules/resources/announcement/modals/sending-confirm/components/sending-confirm.jsx
  plugin/announcement/Resources/modules/resources/announcement/modals/sending-confirm/index.js
  plugin/announcement/Resources/modules/resources/announcement/reducer.js
Labels: AnnouncementBundle

#4514 [ClacoForm] Updates ClacoForm resource app
  main/app/Resources/modules/data/cascade/index.js
  main/app/Resources/modules/data/fields/modals/parameters/components/parameters.jsx
  main/app/Resources/modules/modals/selection/components/modal.jsx
  main/app/Resources/modules/plugin.js
  main/core/Resources/config/routing.yml
  plugin/claco-form/Listener/ClacoFormListener.php
  plugin/claco-form/Resources/modules/modals/category/components/category-form.jsx
  plugin/claco-form/Resources/modules/modals/keyword/components/keyword-form.jsx
  plugin/claco-form/Resources/modules/plugin.js
  plugin/claco-form/Resources/modules/resources/claco-form/bootstrap.js
  plugin/claco-form/Resources/modules/resources/claco-form/components/message.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/components/resource.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/constants.js
  plugin/claco-form/Resources/modules/resources/claco-form/containers/resource.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/editor/components/editor.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/editor/store/actions.js
  plugin/claco-form/Resources/modules/resources/claco-form/editor/store/index.js
  plugin/claco-form/Resources/modules/resources/claco-form/editor/store/reducer.js
  plugin/claco-form/Resources/modules/resources/claco-form/editor/template/actions.js
  plugin/claco-form/Resources/modules/resources/claco-form/editor/template/components/template-form.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/index.js
  plugin/claco-form/Resources/modules/resources/claco-form/player/components/claco-form-main-menu.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entries.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-comments.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-form.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-menu.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/store/actions.js
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/store/index.js
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/store/reducer.js
  plugin/claco-form/Resources/modules/resources/claco-form/prop-types.js
  plugin/claco-form/Resources/modules/resources/claco-form/store/actions.js
  plugin/claco-form/Resources/modules/resources/claco-form/store/index.js
  plugin/claco-form/Resources/modules/resources/claco-form/store/reducer.js
  plugin/claco-form/Resources/modules/resources/claco-form/store/selectors.js
  plugin/claco-form/assets.json
Labels: clacoForm, in progress, needs-changes

#4535 [BlogBundle] Blog fixes
  plugin/blog/Controller/API/PostController.php
  plugin/blog/Installation/Updater/Updater120000.php
  plugin/blog/Resources/config/config.yml
  plugin/blog/Resources/modules/plugin.js
  plugin/blog/Resources/modules/resources/blog/actions/post.js
  plugin/blog/Resources/modules/resources/blog/comment/components/comment.jsx
  plugin/blog/Resources/modules/resources/blog/comment/components/comments.jsx
  plugin/blog/Resources/modules/resources/blog/containers/blog.jsx
  plugin/blog/Resources/modules/resources/blog/editor/components/blog-options.jsx
  plugin/blog/Resources/modules/resources/blog/editor/components/tool-manager.jsx
  plugin/blog/Resources/modules/resources/blog/editor/store/reducer.js
  plugin/blog/Resources/modules/resources/blog/moderation/components/reported.jsx
  plugin/blog/Resources/modules/resources/blog/moderation/components/trusted-users.jsx
  plugin/blog/Resources/modules/resources/blog/moderation/components/unpublished-comments.jsx
  plugin/blog/Resources/modules/resources/blog/moderation/components/unpublished-posts.jsx
  plugin/blog/Resources/modules/resources/blog/moderation/store/reducer.js
  plugin/blog/Resources/modules/resources/blog/player/components/player.jsx
  plugin/blog/Resources/modules/resources/blog/player/components/resource.jsx
  plugin/blog/Resources/modules/resources/blog/post/components/post-form.jsx
  plugin/blog/Resources/modules/resources/blog/post/components/post.jsx
  plugin/blog/Resources/modules/resources/blog/post/components/posts.jsx
  plugin/blog/Resources/modules/resources/blog/post/store/reducer.js
  plugin/blog/Resources/modules/resources/blog/store/index.js
  plugin/blog/Resources/modules/resources/blog/store/reducer.js
  plugin/blog/Resources/modules/resources/blog/store/selectors.js
  plugin/blog/Resources/modules/resources/blog/toolbar/components/archives.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/calendar.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/exporters.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/infobar.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/redactors.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/tags.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/toolbar.jsx
Labels: BlogBundle

#4551 multiple enhancements & fixes on widgets
  main/app/Resources/modules/components/await.jsx
  main/app/Resources/modules/components/embedded.jsx
  main/core/API/Finder/Workspace/WorkspaceFinder.php
  main/core/API/Serializer/Widget/HomeTabSerializer.php
  main/core/API/Serializer/Widget/Type/ResourceWidgetSerializer.php
  main/core/API/Serializer/Widget/WidgetContainerSerializer.php
  main/core/Controller/APINew/Tool/HomeController.php
  main/core/Controller/Widget/MyWorkspacesWidgetController.php
  main/core/Controller/Widget/ResourcesWidgetController.php
  main/core/Controller/Widget/SimpleTextController.php
  main/core/Entity/Tab/HomeTab.php
  main/core/Entity/Widget/Type/ResourceWidget.php
  main/core/Entity/Widget/WidgetContainer.php
  main/core/Listener/Administration/HomeListener.php
  main/core/Listener/Widget/ProfileWidgetListener.php
  main/core/Listener/Widget/ResourcesWidgetListener.php
  main/core/Listener/Widget/SimpleTextWidgetListener.php
  main/core/Listener/Widget/TextResourceListener.php
  main/core/Listener/Widget/WorkspaceWidgetListener.php
  main/core/Resources/config/routing.yml
  main/core/Resources/modules/plugin.js
  main/core/Resources/modules/widget/content/modals/creation/components/modal.jsx
  main/core/Resources/modules/widget/editor/modals/creation/components/modal.jsx
  main/core/Resources/modules/widget/editor/modals/creation/containers/modal.jsx
  main/core/Resources/modules/widget/editor/modals/creation/store/actions.js
  main/core/Resources/modules/widget/types/list/components/parameters.jsx
  main/core/Resources/views/profile/my_profile_widget.html.twig
  main/core/Resources/views/widget/desktop_widget_my_workspaces.html.twig
  main/core/Resources/views/widget/display_my_workspaces_widget.html.twig
  main/core/Resources/views/widget/embed/iframe.html.twig
  main/core/Resources/views/widget/embed/widget.html.twig
  main/core/Resources/views/widget/resource_text_configure_form.html.twig
  main/core/Resources/views/widget/resource_text_display.html.twig
  main/core/Resources/views/widget/resources_widget.html.twig
  main/core/Resources/views/widget/resources_widget_configure_form.html.twig
  main/core/Resources/views/widget/simple_text/configure.html.twig
  main/core/Resources/views/widget/simple_text/display.html.twig
Labels: needs-changes, no-squash

#4555 Adds data sources forum & announcement
  plugin/announcement/Finder/AnnouncementFinder.php
  plugin/announcement/Listener/DataSource/AnnouncementsSource.php
  plugin/announcement/Resources/config/config.yml
  plugin/announcement/Resources/modules/data/components/announcement-card.jsx
  plugin/announcement/Resources/modules/data/sources/announcements.js
  plugin/announcement/Resources/modules/plugin.js
  plugin/announcement/Resources/modules/resources/announcement/bootstrap.js
  plugin/announcement/Resources/modules/resources/announcement/components/announce-form.jsx
  plugin/announcement/Resources/modules/resources/announcement/components/announce-send.jsx
  plugin/announcement/Resources/modules/resources/announcement/components/resource.jsx
  plugin/announcement/Resources/modules/resources/announcement/containers/resource.jsx
  plugin/announcement/Resources/modules/resources/announcement/modals/sending-confirm/components/sending-confirm.jsx
  plugin/announcement/Resources/modules/resources/announcement/store/reducer.js
  plugin/announcement/Resources/modules/resources/announcement/store/selectors.js
  plugin/announcement/Resources/translations/data_sources.de.json
  plugin/announcement/Resources/translations/data_sources.en.json
  plugin/announcement/Resources/translations/data_sources.fr.json
  plugin/announcement/Resources/translations/data_sources.it.json
  plugin/announcement/Resources/translations/data_sources.nl.json
  plugin/announcement/Transfer/AnnouncementImporter.php
  plugin/forum/Controller/API/ForumController.php
  plugin/forum/Controller/API/SubjectController.php
  plugin/forum/Controller/WidgetController.php
  plugin/forum/Finder/MessageFinder.php
  plugin/forum/Form/Widget/LastMessageWidgetConfigType.php
  plugin/forum/Installation/Updater/Updater020200.php
  plugin/forum/Installation/Updater/Updater020210.php
  plugin/forum/Installation/Updater/Updater020300.php
  plugin/forum/Listener/DataSource/ForumMessageSource.php
  plugin/forum/Resources/config/config.yml
  plugin/forum/Resources/modules/data/sources/forum-messages.js
  plugin/forum/Resources/modules/plugin.js
  plugin/forum/Resources/modules/resources/forum/player/components/subject-form.jsx
  plugin/forum/Resources/modules/resources/forum/player/store/actions.js
  plugin/forum/Resources/modules/resources/forum/store/actions.js
  plugin/forum/Resources/modules/resources/forum/store/reducer.js
  plugin/forum/Resources/translations/data_sources.de.json
  plugin/forum/Resources/translations/data_sources.en.json
  plugin/forum/Resources/translations/data_sources.fr.json
  plugin/forum/Resources/translations/data_sources.it.json
  plugin/forum/Resources/translations/data_sources.nl.json
Labels: in progress, needs-changes

#4559 [BlogBundle] Blog fixes + Blog data sources
  plugin/blog/Finder/PostFinder.php
  plugin/blog/Listener/DataSource/BlogPostsSource.php
  plugin/blog/Resources/config/config.yml
  plugin/blog/Resources/modules/data/components/post-card.jsx
  plugin/blog/Resources/modules/data/sources/blog-posts.js
  plugin/blog/Resources/modules/plugin.js
  plugin/blog/Resources/modules/resources/blog/comment/store/reducer.js
  plugin/blog/Resources/modules/resources/blog/player/components/player.jsx
  plugin/blog/Resources/modules/resources/blog/post/components/post.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/archives.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/calendar.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/redactors.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/tags.jsx
  plugin/blog/Resources/translations/data_sources.de.json
  plugin/blog/Resources/translations/data_sources.en.json
  plugin/blog/Resources/translations/data_sources.fr.json
  plugin/blog/Resources/translations/data_sources.it.json
  plugin/blog/Resources/translations/data_sources.nl.json
Labels: BlogBundle

#4572 [ExoBundle] Exo fixes
  plugin/exo/Entity/Exercise.php
  plugin/exo/Manager/Attempt/PaperManager.php
  plugin/exo/Migrations/pdo_mysql/Version20180824150839.php
  plugin/exo/Resources/modules/items/choice/editor.js
  plugin/exo/Resources/modules/quiz/editor/components/quiz-editor.jsx
  plugin/exo/Resources/modules/quiz/player/components/player.jsx
  plugin/exo/Resources/styles/quiz/player.less
  plugin/exo/Resources/translations/quiz.en.json
  plugin/exo/Resources/translations/quiz.fr.json
  plugin/exo/Serializer/ExerciseSerializer.php
  plugin/exo/Serializer/Item/ItemSerializer.php
Labels: ExoBundle

#4597 [CoreBundle] enhances widgets
  main/app/Entity/Parameters/ListParameters.php
  main/app/Resources/modules/content/form/components/actions.jsx
  main/app/Resources/modules/content/list/components/data.jsx
  main/app/Resources/modules/content/list/components/header.jsx
  main/app/Resources/modules/content/list/components/search.jsx
  main/app/Resources/modules/content/list/constants.js
  main/app/Resources/modules/content/list/containers/data.jsx
  main/app/Resources/modules/content/list/store/connect.js
  main/app/Resources/translations/actions.en.json
  main/app/Resources/translations/actions.fr.json
  main/core/API/Serializer/Widget/Type/ListWidgetSerializer.php
  main/core/Migrations/pdo_mysql/Version20180829071934.php
  main/core/Resources/config/config.yml
  main/core/Resources/less/layout/resource/embedded.less
  main/core/Resources/less/layout/resource/index.less
  main/core/Resources/less/widget/index.less
  main/core/Resources/modules/resource/components/embedded.jsx
  main/core/Resources/modules/widget/types/list/components/parameters.jsx
  main/core/Resources/modules/widget/types/list/components/widget.jsx
  main/core/Resources/modules/widget/types/list/containers/widget.jsx
  main/core/Resources/modules/widget/types/list/prop-types.js
  main/core/Resources/modules/widget/types/list/store/selectors.js
  main/core/Resources/modules/widget/types/resource/components/widget.jsx
  main/core/Resources/public/images/data-icons.svg
  main/core/Resources/public/images/widget-icons.svg
  main/core/Resources/translations/widget.en.json
  main/core/Resources/translations/widget.fr.json
  plugin/agenda/Resources/config/config.yml
  plugin/agenda/Resources/translations/platform.de.json
  plugin/agenda/Resources/translations/platform.en.json
  plugin/agenda/Resources/translations/platform.es.json
  plugin/agenda/Resources/translations/platform.fr.json
  plugin/agenda/Resources/translations/platform.it.json
  plugin/agenda/Resources/translations/platform.nl.json
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entries.jsx
  plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/correctors.jsx
  plugin/path/Controller/Widget/PathWidgetController.php
  plugin/path/Form/Type/PathWidgetConfigType.php
  plugin/path/Listener/Widget/PathProgressionListener.php
  plugin/path/Listener/Widget/PathSlideshowListener.php
  plugin/path/Listener/Widget/PathWidgetListener.php
  plugin/path/Manager/WidgetManager.php
  plugin/path/Resources/config/config.yml
  plugin/path/Resources/config/routing.yml
  plugin/path/Resources/styles/resources/path/step.less
  plugin/path/Resources/styles/widgets/path-progression.less
  plugin/path/Resources/styles/widgets/path-slideshow.less
  plugin/path/Resources/translations/widget.de.json
  plugin/path/Resources/translations/widget.en.json
  plugin/path/Resources/translations/widget.es.json
  plugin/path/Resources/translations/widget.fr.json
  plugin/path/Resources/translations/widget.it.json
  plugin/path/Resources/translations/widget.nl.json
  plugin/path/Resources/views/widget/config.html.twig
  plugin/path/Resources/views/widget/progression.html.twig
Labels: needs-changes

#4610 [BlogBundle] Blog fixes
  plugin/blog/Resources/modules/resources/blog/comment/components/comments.jsx
  plugin/blog/Resources/modules/resources/blog/constants.js
  plugin/blog/Resources/modules/resources/blog/player/components/player.jsx
  plugin/blog/Resources/modules/resources/blog/player/components/resource.jsx
  plugin/blog/Resources/modules/resources/blog/post/components/post.jsx
  plugin/blog/Resources/modules/resources/blog/post/components/posts.jsx
  plugin/blog/Resources/modules/resources/blog/store/reducer.js
  plugin/blog/Resources/modules/resources/blog/store/selectors.js
  plugin/blog/Resources/modules/resources/blog/toolbar/components/redactors.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/tags.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/toolbar.jsx
  plugin/blog/Resources/modules/resources/blog/utils.js
  plugin/blog/Resources/styles/resources/blog/index.less
  plugin/blog/Resources/translations/icap_blog.en.json
  plugin/blog/Resources/translations/icap_blog.fr.json
  plugin/blog/assets.json
Labels: BlogBundle
