Repository claroline/Distribution, pull requests merged in 2018-06, with the labels that each got.

#4268 [ExoBundle] Score rules for choice question with multiple answers
  main/core/Controller/ResourceOldController.php
  main/core/Manager/Resource/MaskManager.php
  main/core/Resources/modules/layout/chart/gauge/components/circlular-gauge.jsx
  plugin/exo/Library/Attempt/CorrectedAnswer.php
  plugin/exo/Manager/Attempt/ScoreManager.php
  plugin/exo/Manager/Item/ItemManager.php
  plugin/exo/Resources/modules/data/types/index.js
  plugin/exo/Resources/modules/data/types/score-rules/components/form-group.jsx
  plugin/exo/Resources/modules/data/types/score-rules/index.js
  plugin/exo/Resources/modules/data/types/score-rules/prop-types.js
  plugin/exo/Resources/modules/items/choice/constants.js
  plugin/exo/Resources/modules/items/choice/editor.js
  plugin/exo/Resources/modules/items/choice/editor.jsx
  plugin/exo/Resources/modules/items/choice/index.js
  plugin/exo/Resources/modules/items/choice/paper.jsx
  plugin/exo/Resources/modules/quiz/correction/components/corrected-answer.js
  plugin/exo/Resources/modules/quiz/enums.js
  plugin/exo/Resources/modules/quiz/papers/selectors.js
  plugin/exo/Resources/modules/quiz/papers/utils.js
  plugin/exo/Resources/modules/resources/quiz/components/resource.jsx
  plugin/exo/Resources/styles/components/score-rules.less
  plugin/exo/Resources/styles/main.less
  plugin/exo/Resources/translations/quiz.en.json
  plugin/exo/Resources/translations/quiz.fr.json
  plugin/exo/Resources/views/exercise/open.html.twig
  plugin/exo/Serializer/Item/ItemSerializer.php
  plugin/exo/Tests/Controller/Resource/ExerciseControllerTest.php
Labels: ExoBundle

#4291 [ExoBundle] Questions bank + fixes
  main/core/Manager/Resource/ResourceEvaluationManager.php
  main/core/Resources/modules/layout/evaluation/components/score-gauge.jsx
  plugin/exo/Controller/Api/AttemptController.php
  plugin/exo/Library/Item/Definition/ChoiceDefinition.php
  plugin/exo/Manager/Attempt/PaperManager.php
  plugin/exo/Resources/modules/bank/components/questions.jsx
  plugin/exo/Resources/modules/quiz/player/actions.js
Labels: ExoBundle

#4297 Multiple fixes
  main/core/Listener/Resource/Types/TextListener.php
  main/core/Resources/modules/resources/text/components/resource.jsx
  plugin/survey/ClarolineSurveyBundle.php
Labels: in progress, needs-changes

#4303 [CoreBundle] implements custom resource creation
  main/app/Resources/modules/components/await.jsx
  main/core/API/Serializer/Resource/Types/FileSerializer.php
  main/core/Listener/Resource/Types/FileListener.php
  main/core/Resources/less/layout/modal/index.less
  main/core/Resources/less/layout/resource/index.less
  main/core/Resources/modules/administration/user/location/components/location-list.jsx
  main/core/Resources/modules/administration/user/role/components/role-list.jsx
  main/core/Resources/modules/data/details/components/details.jsx
  main/core/Resources/modules/data/details/prop-types.js
  main/core/Resources/modules/data/form/components/field.jsx
  main/core/Resources/modules/data/form/components/form.jsx
  main/core/Resources/modules/data/form/prop-types.js
  main/core/Resources/modules/data/list/components/view/data-table.jsx
  main/core/Resources/modules/data/list/prop-types.js
  main/core/Resources/modules/data/prop-types.js
  main/core/Resources/modules/plugin.js
  main/core/Resources/modules/resource/components/form.jsx
  main/core/Resources/modules/resource/components/type.jsx
  main/core/Resources/modules/resource/modals/creation/components/parameters.jsx
  main/core/Resources/modules/resource/modals/creation/store/actions.js
  main/core/Resources/modules/resource/modals/creation/store/selectors.js
  main/core/Resources/modules/resources/file/components/creation.jsx
  main/core/Resources/modules/resources/file/index.js
  main/core/Resources/modules/workspace/user/group/components/group-list.jsx
  main/core/Resources/modules/workspace/user/user/components/user-list.jsx
  main/core/Security/Voter/ResourceVoter.php
  plugin/claco-form/Resources/modules/resources/claco-form/editor/components/editor.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entries.jsx
  plugin/cursus/Resources/modules/SessionEventsTool/components/manager-view.jsx
  plugin/cursus/Resources/modules/SessionEventsTool/components/user-view.jsx
  plugin/drop-zone/Resources/modules/plugin/configuration/components/tools.jsx
  plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/correctors.jsx
  plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/drops.jsx
  plugin/exo/Resources/modules/bank/components/questions.jsx
  plugin/exo/Resources/modules/quiz/papers/components/papers.jsx
  plugin/planned-notification/Resources/modules/data/types/message/components/message-form-group.jsx
  plugin/planned-notification/Resources/modules/tools/planned-notification/message/components/messages.jsx
  plugin/planned-notification/Resources/modules/tools/planned-notification/notification/components/notifications.jsx
Labels: needs-changes
