Repository claroline/Distribution, pull requests merged in 2018-09, with the labels that each got.

#4614 Show resource header
  main/app/Resources/modules/page/components/page.jsx
  main/core/API/Serializer/Widget/Type/ResourceWidgetSerializer.php
  main/core/Entity/Widget/Type/ResourceWidget.php
  main/core/Library/Installation/Updater/Updater120000.php
  main/core/Resources/modules/resource/components/embedded.jsx
  main/core/Resources/modules/resource/components/page.jsx
  main/core/Resources/modules/resource/containers/page.jsx
  main/core/Resources/modules/resource/store/selectors.js
  main/core/Resources/modules/widget/content/prop-types.js
  main/core/Resources/modules/widget/content/store/selectors.js
  main/core/Resources/modules/widget/types/resource/components/parameters.jsx
  main/core/Resources/modules/widget/types/resource/components/widget.jsx
  main/core/Resources/modules/widget/types/resource/containers/widget.jsx
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  plugin/path/Entity/Step.php
  plugin/path/Migrations/pdo_mysql/Version20180831141209.php
  plugin/path/Resources/modules/resources/path/editor/components/step-form.jsx
  plugin/path/Resources/modules/resources/path/player/components/player.jsx
  plugin/path/Resources/modules/resources/path/player/components/step.jsx
  plugin/path/Resources/modules/resources/path/prop-types.js
  plugin/path/Serializer/PathSerializer.php
Labels: in progress

#4645 Multiple fixes on resources
  main/core/API/Serializer/Resource/ResourceNodeSerializer.php
  main/core/Manager/Resource/RightsManager.php
  main/core/Resources/less/layout/resource/embedded.less
  main/core/Resources/less/layout/resource/index.less
  main/core/Resources/modules/resources/directory/components/resource.jsx
  main/core/Resources/modules/resources/file/components/resource.jsx
  main/core/Resources/modules/resources/text/components/resource.jsx
  main/core/Tests/Unit/Manager/RightsManagerTest.php
  plugin/announcement/Resources/modules/resources/announcement/components/resource.jsx
  plugin/bibliography/Resources/modules/resources/book-reference/components/resource.jsx
  plugin/big-blue-button/Resources/modules/bbb/components/bbb-resource.jsx
  plugin/blog/Resources/modules/resources/blog/player/components/resource.jsx
  plugin/blog/Resources/styles/resources/blog/index.less
  plugin/claco-form/Resources/modules/resources/claco-form/components/resource.jsx
  plugin/drop-zone/Resources/modules/resources/dropzone/components/resource.jsx
  plugin/exo/Resources/modules/resources/quiz/components/resource.jsx
  plugin/forum/Resources/modules/resources/forum/components/resource.jsx
  plugin/path/Resources/modules/resources/path/components/resource.jsx
  plugin/scorm/Resources/modules/resources/scorm/components/resource.jsx
  plugin/url/Resources/modules/resources/url/components/resource.jsx
  plugin/web-resource/Resources/modules/resources/web-resource/components/resource.jsx
  plugin/wiki/Resources/modules/resources/wiki/components/resource.jsx
Labels: needs-changes, no-squash

#4634 [ForumBundle] cascade delete for users
  main/app/Persistence/ObjectManager.php
  main/core/Command/Removal/RemoveWorkspaceCommand.php
  main/core/Entity/Resource/ResourceType.php
  main/core/Manager/ResourceManager.php
  main/core/Manager/WorkspaceManager.php
  plugin/dropzone/Listener/DropzoneListener.php
  plugin/forum/Entity/Validation/User.php
  plugin/forum/Migrations/pdo_mysql/Version20180904171934.php
Labels: needs-changes

#4680 Deactivates badge listener on every logs
  plugin/badge/Listener/BadgeListener.php
Labels: BadgeBundle

#4720 [CoreBundle] Resource restrictions
  main/app/Resources/modules/overlay/header/components/header.jsx
  main/app/Resources/modules/overlay/header/components/notifications.jsx
  main/app/Resources/modules/overlay/header/components/workspaces.jsx
  main/core/API/Serializer/Resource/ResourceNodeSerializer.php
  main/core/Controller/APINew/Resource/ResourceNodeController.php
  main/core/Controller/LocaleController.php
  main/core/Manager/Resource/ResourceRestrictionsManager.php
  main/core/Resources/modules/resource/components/form.jsx
  main/core/Resources/modules/resource/components/page.jsx
  main/core/Resources/modules/resource/components/restrictions.jsx
  main/core/Resources/modules/resource/containers/page.jsx
  main/core/Resources/modules/resource/store/actions.js
Labels: needs-changes

#4726 Improves user tracking
  main/core/API/Finder/Resource/ResourceUserEvaluationFinder.php
  main/core/Controller/APINew/User/UserTrackingController.php
  main/core/Resources/less/users/index.less
  main/core/Resources/less/users/timeline.less
  main/core/Resources/less/users/tracking.less
  main/core/Resources/modules/user/tracking/components/main.jsx
  main/core/Resources/modules/user/tracking/components/search.jsx
  main/core/Resources/modules/user/tracking/components/summary.jsx
  main/core/Resources/modules/user/tracking/components/timeline.jsx
  main/core/Resources/modules/user/tracking/index.js
  main/core/Resources/modules/user/tracking/reducer.js
  main/core/Resources/modules/user/tracking/store/actions.js
  main/core/Resources/modules/user/tracking/store/index.js
  main/core/Resources/modules/user/tracking/store/reducer.js
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
Labels: in progress, needs-changes

#4758 [AnnouncementBundle] Adds a voter for announcement
  plugin/announcement/Security/Voter/AnnouncementVoter.php
Labels: AnnouncementBundle

#4788 [CollecticielBundle] Fixes selectors name
  plugin/collecticiel/Resources/modules/resources/collecticiel/store/selectors.js
Labels: CollecticielBundle

#4806 [PathBundle] Redirects to main parameters when deleting current step
  plugin/path/Resources/modules/resources/path/editor/components/editor.jsx
Labels: PathBundle

#4821 [ExoBundle] Fixes search on question title/content in questions bank
  plugin/exo/Resources/modules/bank/components/questions.jsx
Labels: ExoBundle

#4828 [AnnouncementBundle] Refactors saving of announcement
  plugin/announcement/Resources/modules/resources/announcement/components/announce-form.jsx
Labels: AnnouncementBundle

#4844 [ForumBundle] Fixes subject voter
  plugin/forum/Security/SubjectVoter.php
Labels: ForumBundle

#4848 Fixes papers list
  plugin/exo/Resources/modules/quiz/papers/components/papers.jsx
  plugin/exo/Resources/modules/quiz/papers/reducer.js
Labels: ExoBundle

#4849 [ExoBundle] Fixes docimology
  plugin/exo/Controller/Api/ExerciseController.php
  plugin/exo/Resources/modules/docimology/components/docimology.jsx
  plugin/exo/Resources/modules/resources/quiz/components/resource.jsx
Labels: ExoBundle

#4831 [CursusBundle] Refactoring cursus
  plugin/cursus/Controller/APINew/CursusController.php
  plugin/cursus/Entity/Cursus.php
  plugin/cursus/Finder/CursusFinder.php
  plugin/cursus/Resources/modules/administration/cursus/course/store/actions.js
  plugin/cursus/Resources/modules/administration/cursus/cursus/components/cursus-tab.jsx
  plugin/cursus/Resources/modules/administration/cursus/cursus/components/cursus.jsx
  plugin/cursus/Resources/modules/administration/cursus/cursus/store/actions.js
  plugin/cursus/Serializer/CursusSerializer.php
Labels: CursusBundle, in progress

#4853 [ExoBundle] Fixes manual correction
  plugin/exo/Controller/Api/CorrectionController.php
  plugin/exo/Resources/modules/quiz/correction/actions.js
  plugin/exo/Resources/modules/quiz/correction/components/questions.jsx
  plugin/exo/Resources/modules/quiz/correction/selectors.js
Labels: ExoBundle

#4858 [ClacoForm] Clacoform fixes
  main/core/Resources/modules/layout/modal/index.js
  main/core/Resources/modules/layout/modal/user-picker/components/user-picker.jsx
  main/core/Resources/modules/layout/modal/user-picker/index.js
  main/core/Resources/modules/layout/typeahead/users/typeahead.jsx
  plugin/claco-form/Finder/EntryFinder.php
  plugin/claco-form/Resources/modules/modals/category/components/category-form.jsx
  plugin/claco-form/Resources/modules/modals/keyword/components/keyword-form.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/editor/components/editor.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entries.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry-form.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/entry/components/entry.jsx
  plugin/claco-form/Security/Voter/KeywordVoter.php
  plugin/claco-form/Serializer/ClacoFormSerializer.php
Labels: clacoForm

#4863 [ClacoForm] Clacoform rights fix
  plugin/claco-form/Resources/modules/resources/claco-form/store/selectors.js
Labels: clacoForm

#4865 [ClacoFormBundle] Fixes category association
  plugin/claco-form/Resources/modules/resources/claco-form/editor/components/category-fields-values.jsx
Labels: clacoForm
