Repository claroline/Distribution, pull requests merged in 2019-03, with the labels that each got.

#5612 [ScormBundle] Fixes undefined value for LMSGetValue
  plugin/scorm/Resources/modules/resources/scorm/player/api.js
Labels: ScormBundle

#5618 [ScormBundle] Refactors UploadedFile to File
  plugin/scorm/Manager/ScormManager.php
Labels: ScormBundle

#5619 [LessonBundle] Fixes Lesson creation
  plugin/lesson/Serializer/LessonSerializer.php
Labels: LessonBundle

#5620 [ExoBundle] Fixes exo creation
  plugin/exo/Serializer/ExerciseSerializer.php
Labels: ExoBundle

#5624 [PathBundle] Fixes path serializer and schema for resource creation
  plugin/path/Resources/schemas/path.json
  plugin/path/Serializer/PathSerializer.php
Labels: PathBundle

#5631 Fixes Text & Blog creation
  main/core/API/Serializer/Resource/Types/TextSerializer.php
  plugin/blog/Resources/schemas/blog.json
  plugin/blog/Serializer/BlogOptionsSerializer.php
  plugin/blog/Serializer/BlogSerializer.php
Labels: BlogBundle, CoreBundle

#5632 [WikiBundle] Fixes Wiki creation & opening
  plugin/wiki/Repository/SectionRepository.php
  plugin/wiki/Serializer/WikiSerializer.php
Labels: WikiBundle

#5638 [DropZoneBundle] Fixes correction reporting
  plugin/drop-zone/Event/Log/LogCorrectionReportEvent.php
  plugin/drop-zone/Event/Log/LogDropReportEvent.php
Labels: EvaluationBundle

#5649 This code should not have been removed.
  main/core/Manager/ResourceManager.php
  main/core/Manager/Workspace/WorkspaceManager.php
Labels: urgent

#5654 [!!! NEW MIGRATIONS !!!][CoreBundle] Adds comments on ResourceNode
  main/app/Resources/modules/content/form/containers/data.jsx
  main/core/API/Serializer/Resource/ResourceCommentSerializer.php
  main/core/API/Serializer/Resource/ResourceNodeSerializer.php
  main/core/API/Serializer/Resource/Types/FileSerializer.php
  main/core/Controller/APINew/Resource/ResourceCommentController.php
  main/core/Entity/Resource/ResourceComment.php
  main/core/Entity/Resource/ResourceNode.php
  main/core/Migrations/pdo_mysql/Version20190313151535.php
  main/core/Resources/modules/files/prop-types.js
  main/core/Resources/modules/layout/comment/components/comments.jsx
  main/core/Resources/modules/resource/prop-types.js
  main/core/Resources/modules/resource/store/actions.js
  main/core/Resources/modules/resource/store/reducer.js
  main/core/Resources/modules/resources/file/components/resource.jsx
  main/core/Resources/modules/resources/file/containers/resource.jsx
  main/core/Resources/modules/resources/file/editor/components/editor.jsx
  main/core/Resources/modules/resources/file/player/components/player.jsx
  main/core/Resources/modules/resources/file/store/actions.js
  main/core/Resources/modules/resources/file/store/reducer.js
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  main/core/Security/Voter/ResourceCommentVoter.php
Labels: CoreBundle

#5699 [PathBundle] Path dashboard + steps deserialization fix
  main/core/API/Finder/Resource/ResourceUserEvaluationFinder.php
  main/core/Resources/modules/resource/prop-types.js
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  plugin/path/Controller/API/PathController.php
  plugin/path/Manager/UserProgressionManager.php
  plugin/path/Resources/modules/resources/path/components/resource.jsx
  plugin/path/Resources/modules/resources/path/dashboard/components/main.jsx
  plugin/path/Resources/modules/resources/path/dashboard/containers/main.jsx
  plugin/path/Resources/modules/resources/path/dashboard/store/actions.js
  plugin/path/Resources/modules/resources/path/dashboard/store/index.js
  plugin/path/Resources/modules/resources/path/dashboard/store/reducer.js
  plugin/path/Resources/modules/resources/path/dashboard/store/selectors.js
  plugin/path/Resources/modules/resources/path/modals/user-progression/components/modal.jsx
  plugin/path/Resources/modules/resources/path/modals/user-progression/containers/modal.jsx
  plugin/path/Resources/modules/resources/path/modals/user-progression/index.js
  plugin/path/Resources/modules/resources/path/store/reducer.js
  plugin/path/Serializer/PathSerializer.php
Labels: PathBundle
