Repository claroline/Distribution, pull requests merged in 2019-09, with the labels that each got.

#6106 multiple fixes
  main/app/Resources/translations/actions.en.json
  main/app/Resources/translations/actions.fr.json
  main/authentication/Library/PlatformDefaults.php
  main/authentication/Listener/Oauth/ExternalAuthenticationListener.php
  main/core/Library/Installation/Updater/Updater120500.php
  main/core/Resources/modules/resource/permissions.js
  plugin/agenda/Resources/modules/data/sources/tasks.js
  plugin/agenda/Resources/modules/event/components/micro.jsx
  plugin/agenda/Resources/modules/event/modals/about/components/modal.jsx
  plugin/agenda/Resources/modules/event/modals/parameters/components/modal.jsx
  plugin/agenda/Resources/modules/event/modals/parameters/containers/modal.jsx
  plugin/agenda/Resources/modules/event/prop-types.js
  plugin/agenda/Resources/modules/tools/agenda/components/tool.jsx
  plugin/agenda/Resources/modules/tools/agenda/store/actions.js
  plugin/agenda/Resources/modules/tools/agenda/views/month/components/view.jsx
  plugin/agenda/Resources/styles/event.less
  plugin/agenda/Serializer/EventSerializer.php
Labels: in progress, no-squash

#6135 Fixes in ClacoForm
  plugin/claco-form/Manager/ClacoFormManager.php
  plugin/claco-form/Resources/modules/resources/claco-form/actions/add-entry.js
  plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry.jsx
  plugin/claco-form/Serializer/EntrySerializer.php
Labels: ClacoFormBundle

#6136 Fixes publication date
  plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry.jsx
  plugin/claco-form/Serializer/EntrySerializer.php
Labels: ClacoFormBundle

#6185 Adds updater for default score to success of path
  main/core/Library/Configuration/PlatformDefaults.php
  main/core/Library/Installation/Updater/Updater120503.php
  plugin/path/Installation/AdditionalInstaller.php
  plugin/path/Installation/Updater/Updater120503.php
Labels: PathBundle
