Repository claroline/Distribution, pull requests merged in 2019-10, with the labels that each got.

#6240 Multiple fixes & upgrades for exo
  main/core/Resources/modules/data/types/resource/components/input.jsx
  plugin/audio-player/Entity/Resource/Section.php
  plugin/audio-player/Migrations/pdo_mysql/Version20191002143105.php
  plugin/audio-player/Resources/modules/files/audio/components/editor.jsx
  plugin/audio-player/Resources/modules/files/audio/components/player.jsx
  plugin/audio-player/Resources/modules/files/audio/prop-types.js
  plugin/audio-player/Resources/modules/quiz/items/waveform/components/editor.jsx
  plugin/audio-player/Resources/modules/quiz/items/waveform/components/feedback.jsx
  plugin/audio-player/Resources/modules/quiz/items/waveform/components/paper.jsx
  plugin/audio-player/Resources/modules/quiz/items/waveform/components/player.jsx
  plugin/audio-player/Resources/modules/quiz/items/waveform/prop-types.js
  plugin/audio-player/Resources/modules/waveform/components/waveform.jsx
  plugin/audio-player/Resources/translations/audio.en.json
  plugin/audio-player/Resources/translations/audio.fr.json
  plugin/audio-player/Serializer/Quiz/WaveformQuestionSerializer.php
  plugin/audio-player/Serializer/Resource/SectionSerializer.php
  plugin/exo/Resources/modules/contents/resource/components/editor.jsx
  plugin/exo/Resources/modules/contents/resource/components/modal.jsx
  plugin/exo/Resources/modules/contents/resource/components/player.jsx
  plugin/exo/Resources/modules/contents/resource/components/thumbnail.jsx
  plugin/exo/Resources/modules/contents/resource/index.js
  plugin/exo/Resources/modules/contents/utils.js
  plugin/exo/Resources/modules/items/cloze/index.js
  plugin/exo/Resources/modules/plugin.js
  plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
  plugin/exo/Resources/translations/question_types.en.json
  plugin/exo/Resources/translations/question_types.fr.json
  plugin/exo/Resources/translations/quiz.en.json
  plugin/exo/Resources/translations/quiz.fr.json
  plugin/exo/Serializer/Item/Type/ContentItemSerializer.php
Labels: ExoBundle, new migrations

#6245 Adds filter for resource types when selecting resource content in quiz
  plugin/exo/Resources/modules/contents/resource/components/editor.jsx
Labels: ExoBundle

#6266 Displays label if value is true for boolean type
  plugin/claco-form/Controller/API/CategoryController.php
  plugin/claco-form/Controller/API/EntryController.php
  plugin/claco-form/Controller/API/KeywordController.php
  plugin/claco-form/Controller/ClacoFormController.php
  plugin/claco-form/Resources/config/services/controller.yml
  plugin/claco-form/Resources/modules/resources/claco-form/template.js
Labels: ClacoFormBundle

#6276 Refactors category association to field values
  plugin/claco-form/Resources/modules/modals/category/components/form.jsx
  plugin/claco-form/Resources/modules/modals/category/containers/form.jsx
  plugin/claco-form/Serializer/FieldChoiceCategorySerializer.php
Labels: ClacoFormBundle

#6292 Fixes test mode when there are content items
  plugin/exo/Resources/modules/quiz/player/components/player.jsx
  plugin/exo/Resources/modules/quiz/player/components/restrictions.jsx
  plugin/exo/Resources/modules/resources/quiz/papers/score.js
Labels: ExoBundle

#6291 [FavouriteBundle] Migrate configs
  plugin/favourite/Controller/FavouriteController.php
  plugin/favourite/DependencyInjection/HeVinciFavouriteExtension.php
  plugin/favourite/Listener/DataSource/MyFavouritesSource.php
  plugin/favourite/Listener/UserListener.php
  plugin/favourite/Manager/FavouriteManager.php
  plugin/favourite/Resources/config/services.yml
Labels: wait-to-merge

#6293 [CompetencyBundle] Migrate configs.
  plugin/competency/Controller/API/AbilityController.php
  plugin/competency/Controller/API/CompetencyController.php
  plugin/competency/Controller/MyObjectiveController.php
  plugin/competency/Listener/Administration/CompetenciesListener.php
  plugin/competency/Listener/PluginListener.php
  plugin/competency/Listener/ResourceListener.php
  plugin/competency/Listener/UserListener.php
  plugin/competency/Manager/CompetencyManager.php
  plugin/competency/Manager/ObjectiveManager.php
  plugin/competency/Manager/ProgressManager.php
  plugin/competency/Manager/ResourceManager.php
  plugin/competency/Resources/config/services.yml
  plugin/competency/Resources/config/services/controller.yml
  plugin/competency/Resources/config/services/listener.yml
  plugin/competency/Resources/config/services/manager.yml
  plugin/competency/Tests/Manager/ProgressManagerTest.php
  plugin/competency/Tests/Transfer/ConverterTest.php
  plugin/competency/Transfer/Converter.php
Labels: wait-to-merge

#6304 Fixes cloze text edition
  plugin/exo/Resources/modules/items/cloze/components/editor.jsx
Labels: ExoBundle

#6315 Many fixes for edition of cloze question
  plugin/exo/Resources/modules/items/cloze/components/editor.jsx
  plugin/exo/Serializer/Item/Type/ClozeQuestionSerializer.php
Labels: ExoBundle

#6321 Fixes event finder & voter
  plugin/agenda/Controller/EventController.php
  plugin/agenda/Finder/EventFinder.php
  plugin/agenda/Security/Voter/EventVoter.php
Labels: AgendaBundle

#6323 Fixes correction reducer in exo
  plugin/exo/Resources/modules/resources/quiz/correction/store/reducer.js
Labels: ExoBundle

#6329 Renames Updater 12.4.14 to 12.4.21
  main/core/Entity/Workspace/Workspace.php
  main/core/Library/Installation/AdditionalInstaller.php
  main/core/Library/Installation/Updater/Updater120421.php
  main/core/Migrations/pdo_mysql/Version20190814143949.php
Labels: CoreBundle

#6330 Fixes tag picking in test mode
  plugin/exo/Resources/modules/resources/quiz/player/attempt.js
Labels: ExoBundle

#6331 multiple fixes
  main/app/Resources/modules/content/list/store/connect.js
  main/core/Resources/modules/data/types/group/components/input.jsx
  plugin/exo/Manager/Attempt/PaperManager.php
  plugin/exo/Manager/AttemptManager.php
  plugin/pdf-player/Resources/modules/files/pdf/components/player.jsx
Labels: no-squash

#6332 Prevents creation of tag if name is already in use + fixes tag fetching
  plugin/tag/Controller/TagController.php
  plugin/tag/Manager/TagManager.php
  plugin/tag/Repository/TagRepository.php
Labels: TagBundle

#6174 Workspace evaluation
  main/core/API/Finder/Workspace/EvaluationFinder.php
  main/core/API/Finder/Workspace/RequirementsFinder.php
  main/core/API/Serializer/Workspace/EvaluationSerializer.php
  main/core/API/Serializer/Workspace/RequirementsSerializer.php
  main/core/Controller/APINew/Workspace/EvaluationController.php
  main/core/Controller/APINew/Workspace/RequirementsController.php
  main/core/Entity/AbstractEvaluation.php
  main/core/Entity/Resource/ResourceEvaluation.php
  main/core/Entity/Resource/ResourceUserEvaluation.php
  main/core/Entity/Workspace/Evaluation.php
  main/core/Entity/Workspace/Requirements.php
  main/core/Listener/Log/LogListener.php
  main/core/Listener/Resource/Types/FileListener.php
  main/core/Listener/Workspace/EvaluationListener.php
  main/core/Manager/Resource/ResourceEvaluationManager.php
  main/core/Manager/Workspace/EvaluationManager.php
  main/core/Migrations/pdo_mysql/Version20191004153353.php
  main/core/Resources/config/services/controller.yml
  main/core/Resources/config/services/finder.yml
  main/core/Resources/config/services/listener.yml
  main/core/Resources/config/services/manager.yml
  main/core/Resources/config/services/serializer.yml
  main/core/Resources/modules/workspace/prop-types.js
  main/core/Resources/translations/platform.en.json
  main/core/Resources/translations/platform.fr.json
  plugin/analytics/Resources/config/services/controller.yml
  plugin/analytics/Resources/modules/analytics/resource/requirements/components/requirements.jsx
  plugin/analytics/Resources/modules/analytics/resource/requirements/containers/requirements.jsx
  plugin/analytics/Resources/modules/analytics/resource/requirements/index.js
  plugin/analytics/Resources/modules/analytics/resource/requirements/store/actions.js
  plugin/analytics/Resources/modules/analytics/resource/requirements/store/index.js
  plugin/analytics/Resources/modules/analytics/resource/requirements/store/reducer.js
  plugin/analytics/Resources/modules/plugin.js
  plugin/analytics/Resources/modules/resource/dashboard/store/reducer.js
  plugin/analytics/Resources/modules/tools/dashboard/components/evaluations.jsx
  plugin/analytics/Resources/modules/tools/dashboard/components/menu.jsx
  plugin/analytics/Resources/modules/tools/dashboard/components/requirements-details.jsx
  plugin/analytics/Resources/modules/tools/dashboard/components/requirements.jsx
  plugin/analytics/Resources/modules/tools/dashboard/components/tool.jsx
  plugin/analytics/Resources/modules/tools/dashboard/containers/requirements-details.jsx
  plugin/analytics/Resources/modules/tools/dashboard/containers/requirements.jsx
  plugin/analytics/Resources/modules/tools/dashboard/containers/tool.jsx
  plugin/analytics/Resources/modules/tools/dashboard/store/actions.js
  plugin/analytics/Resources/modules/tools/dashboard/store/reducer.js
  plugin/analytics/Resources/modules/tools/dashboard/store/selectors.js
  plugin/analytics/Resources/translations/analytics.en.json
  plugin/analytics/Resources/translations/analytics.fr.json
  plugin/blog/Listener/BlogListener.php
  plugin/blog/Manager/BlogTrackingManager.php
  plugin/competency/Tests/Manager/ProgressManagerTest.php
  plugin/competency/Tests/Repository/AbilityRepositoryTest.php
  plugin/drop-zone/Manager/DropzoneManager.php
  plugin/exo/Manager/Attempt/PaperManager.php
  plugin/forum/Listener/Resource/ForumListener.php
  plugin/path/Manager/UserProgressionManager.php
  plugin/wiki/Listener/Resource/WikiListener.php
Labels: new migrations
