Repository claroline/Distribution, pull requests merged in 2019-11, with the labels that each got.

#6391 Updates badge
  plugin/open-badge/Resources/modules/tools/badges/badge/components/form.jsx
  plugin/open-badge/Resources/modules/tools/badges/store/actions.js
Labels: BadgeBundle

#6393 Fixes team params creation
  plugin/team/Manager/TeamManager.php
Labels: TeamBundle

#6416 [CoreBundle] fixes home edition when empty
  main/core/Resources/modules/tools/home/editor/store/reducer.js
  main/core/Resources/modules/tools/home/editor/store/selectors.js
  main/core/Resources/modules/tools/home/player/components/tab.jsx
  main/core/Resources/modules/tools/home/player/containers/main.jsx
  main/core/Resources/modules/tools/home/store/actions.js
Labels: needs-changes

#6421 Fixes type filter in clacoform
  plugin/claco-form/Finder/EntryFinder.php
  plugin/claco-form/Resources/modules/data/sources/entries.js
Labels: ClacoFormBundle

#6422 Fixes configured filters in clacoform
  plugin/claco-form/Finder/EntryFinder.php
  plugin/claco-form/Resources/modules/resources/claco-form/player/store/reducer.js
Labels: ClacoFormBundle

#6430 Many fixes for clacoform
  main/app/Resources/modules/data/types/fields/components/input.jsx
  plugin/claco-form/Command/RefactorTemplatesCommand.php
  plugin/claco-form/Controller/ClacoFormController.php
  plugin/claco-form/Installation/AdditionalInstaller.php
  plugin/claco-form/Installation/Updater/Updater120513.php
  plugin/claco-form/Manager/ClacoFormManager.php
  plugin/claco-form/Resources/config/services/controller.yml
  plugin/claco-form/Resources/modules/resources/claco-form/permissions.js
  plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry-form.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/store/selectors.js
  plugin/claco-form/Resources/modules/resources/claco-form/template.js
  plugin/claco-form/Security/Voter/EntryVoter.php
Labels: ClacoFormBundle

#6433 Blog fixes
  plugin/blog/Resources/modules/data/sources/blog-posts.js
  plugin/blog/Resources/modules/resources/blog/post/components/posts.jsx
  plugin/blog/Serializer/PostSerializer.php
Labels: BlogBundle

#6457 Fixes validation of match question
  plugin/exo/Resources/modules/items/match/index.js
Labels: ExoBundle

#6465 Fixes blog post comments
  plugin/blog/Controller/API/CommentController.php
  plugin/blog/Resources/modules/resources/blog/post/components/card.jsx
  plugin/blog/Resources/modules/resources/blog/post/components/prop-types.js
Labels: BlogBundle
