Repository claroline/Distribution, pull requests merged in 2019-04, with the labels that each got.

#5720 [ExoBundle] Multiple fixes + adds an option to disable response edition once answered
  plugin/exo/Entity/Exercise.php
  plugin/exo/Installation/AdditionalInstaller.php
  plugin/exo/Installation/Updater/Updater120400.php
  plugin/exo/Library/Item/Definition/OrderingDefinition.php
  plugin/exo/Library/Item/Definition/PairDefinition.php
  plugin/exo/Library/Item/Definition/SelectionDefinition.php
  plugin/exo/Migrations/pdo_mysql/Version20190401140211.php
  plugin/exo/Resources/modules/items/choice/components/player.jsx
  plugin/exo/Resources/modules/items/cloze/components/holes.jsx
  plugin/exo/Resources/modules/items/cloze/components/player.jsx
  plugin/exo/Resources/modules/items/cloze/components/stats.jsx
  plugin/exo/Resources/modules/items/graphic/components/paper.jsx
  plugin/exo/Resources/modules/items/graphic/components/player.jsx
  plugin/exo/Resources/modules/items/grid/components/editor.jsx
  plugin/exo/Resources/modules/items/grid/components/feedback.jsx
  plugin/exo/Resources/modules/items/grid/components/paper.jsx
  plugin/exo/Resources/modules/items/grid/components/player.jsx
  plugin/exo/Resources/modules/items/grid/constants.js
  plugin/exo/Resources/modules/items/grid/index.js
  plugin/exo/Resources/modules/items/grid/prop-types.js
  plugin/exo/Resources/modules/items/match/components/feedback.jsx
  plugin/exo/Resources/modules/items/match/components/paper.jsx
  plugin/exo/Resources/modules/items/match/components/player.jsx
  plugin/exo/Resources/modules/items/match/components/player.test.js
  plugin/exo/Resources/modules/items/open/components/player.jsx
  plugin/exo/Resources/modules/items/ordering/components/paper.jsx
  plugin/exo/Resources/modules/items/ordering/components/player.jsx
  plugin/exo/Resources/modules/items/pair/components/player.jsx
  plugin/exo/Resources/modules/items/pair/utils.js
  plugin/exo/Resources/modules/items/selection/components/paper.jsx
  plugin/exo/Resources/modules/items/selection/components/player.jsx
  plugin/exo/Resources/modules/items/selection/utils/selection-input.jsx
  plugin/exo/Resources/modules/items/set/components/paper.jsx
  plugin/exo/Resources/modules/items/set/components/player.jsx
  plugin/exo/Resources/modules/items/words/components/feedback.jsx
  plugin/exo/Resources/modules/items/words/components/paper.jsx
  plugin/exo/Resources/modules/items/words/components/player.jsx
  plugin/exo/Resources/modules/quiz/player/components/player.jsx
  plugin/exo/Resources/modules/resources/quiz/editor/components/parameters.jsx
  plugin/exo/Resources/modules/resources/quiz/editor/components/summary.jsx
  plugin/exo/Resources/translations/quiz.en.json
  plugin/exo/Resources/translations/quiz.fr.json
  plugin/exo/Serializer/ExerciseSerializer.php
Labels: ExoBundle

#5738 [ExoBundle] Fixes end page + default hint penalty
  plugin/exo/Resources/modules/items/components/editor.jsx
  plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
  plugin/exo/Serializer/Item/HintSerializer.php
  plugin/exo/Tests/Serializer/Item/HintSerializerTest.php
Labels: ExoBundle

#5751 [ClarolineDropZoneBundle] Mulitple fixes
  main/core/Listener/Log/LogListener.php
  main/core/Manager/Resource/ResourceEvaluationManager.php
  plugin/blog/Manager/BlogTrackingManager.php
  plugin/drop-zone/ClarolineDropZoneBundle.php
  plugin/drop-zone/Controller/API/DropController.php
  plugin/drop-zone/Controller/API/DropzoneController.php
  plugin/drop-zone/Entity/Correction.php
  plugin/drop-zone/Entity/Document.php
  plugin/drop-zone/Entity/Drop.php
  plugin/drop-zone/Entity/Dropzone.php
  plugin/drop-zone/Installation/AdditionalInstaller.php
  plugin/drop-zone/Installation/Updater/Updater120402.php
  plugin/drop-zone/Listener/Resource/DropzoneListener.php
  plugin/drop-zone/Manager/DropzoneManager.php
  plugin/drop-zone/Migrations/pdo_mysql/Version20190409120322.php
  plugin/drop-zone/Repository/DropRepository.php
  plugin/drop-zone/Resources/modules/resources/dropzone/editor/components/editor.jsx
  plugin/drop-zone/Resources/modules/resources/dropzone/overview/components/overview.jsx
  plugin/drop-zone/Resources/modules/resources/dropzone/player/components/my-drop.jsx
  plugin/drop-zone/Resources/modules/resources/dropzone/prop-types.js
  plugin/drop-zone/Resources/translations/dropzone.en.json
  plugin/drop-zone/Resources/translations/dropzone.fr.json
  plugin/drop-zone/Serializer/CorrectionSerializer.php
  plugin/drop-zone/Serializer/DropSerializer.php
  plugin/drop-zone/Serializer/DropzoneSerializer.php
  plugin/exo/Manager/Attempt/PaperManager.php
  plugin/path/Manager/UserProgressionManager.php
  plugin/scorm/Manager/ScormManager.php
Labels: EvaluationBundle

#5774 [ExoBundle] Fixes item objects
  plugin/exo/Entity/Item/Item.php
  plugin/exo/Resources/modules/contents/audio/index.js
  plugin/exo/Resources/modules/contents/components/content-thumbnail-drag-preview.jsx
  plugin/exo/Resources/modules/contents/components/content-thumbnail.jsx
  plugin/exo/Resources/modules/contents/image/index.js
  plugin/exo/Resources/modules/contents/modals/components/modal.jsx
  plugin/exo/Resources/modules/contents/modals/index.js
  plugin/exo/Resources/modules/contents/utils.js
  plugin/exo/Resources/modules/contents/video/index.js
  plugin/exo/Resources/modules/data/types/medias/components/input.jsx
  plugin/exo/Resources/modules/data/types/medias/modals/editor/components/modal.jsx
  plugin/exo/Resources/modules/data/types/medias/modals/editor/containers/modal.jsx
  plugin/exo/Resources/modules/data/types/medias/modals/editor/index.js
  plugin/exo/Resources/modules/data/types/medias/modals/editor/store/actions.js
  plugin/exo/Resources/modules/data/types/medias/modals/editor/store/index.js
  plugin/exo/Resources/modules/items/components/editor.jsx
  plugin/exo/Resources/modules/quiz/editor/components/content-input.jsx
  plugin/exo/Resources/modules/quiz/editor/components/item-objects-editor.jsx
  plugin/exo/Resources/modules/quiz/editor/components/modal/add-content-modal.jsx
  plugin/exo/Resources/modules/quiz/player/components/player.jsx
  plugin/exo/Resources/modules/resources/quiz/index.js
  plugin/exo/Serializer/Item/ItemSerializer.php
  plugin/exo/Validator/JsonSchema/Item/Type/GridQuestionValidator.php
Labels: ExoBundle

#5784 Fixes deserialization issue in DropZoneBundle
  plugin/drop-zone/Manager/DropzoneManager.php
Labels: EvaluationBundle

#5785 [ExoBundle] Fixes type bug in Paper Generator
  plugin/exo/Library/Attempt/PaperGenerator.php
Labels: ExoBundle

#5788 [DropZoneBundle] Fixes correction creation by manager
  plugin/drop-zone/Serializer/CorrectionSerializer.php
Labels: EvaluationBundle

#5814 [PathBundle] fixes path copy
  main/core/Manager/ResourceManager.php
  plugin/claco-form/Entity/ClacoForm.php
  plugin/claco-form/Listener/Resource/ClacoFormListener.php
  plugin/claco-form/Manager/ClacoFormManager.php
  plugin/exo/Serializer/ExerciseSerializer.php
  plugin/path/Entity/Path/Path.php
  plugin/path/Entity/Step.php
  plugin/path/Listener/Resource/PathListener.php
  plugin/path/Serializer/PathSerializer.php
Labels: in progress
