Repository claroline/Distribution, pull requests merged in 2019-02, with the labels that each got.

#5499 Multiple UI fixes
  main/core/Resources/translations/platform.fr.json
  main/core/Resources/translations/validators.fr.json
  plugin/claco-form/Entity/ClacoForm.php
  plugin/claco-form/Resources/modules/resources/claco-form/components/message.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/editor/components/editor.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/editor/store/actions.js
  plugin/claco-form/Resources/modules/resources/claco-form/player/components/entries.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry-form-data.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry-form.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry-menu.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry.jsx
  plugin/claco-form/Resources/modules/resources/claco-form/store/selectors.js
  plugin/claco-form/Resources/modules/resources/claco-form/utils.js
  plugin/claco-form/Resources/styles/resources/claco-form.less
  plugin/claco-form/Resources/translations/clacoform.en.json
  plugin/claco-form/Resources/translations/clacoform.fr.json
  plugin/claco-form/Serializer/ClacoFormSerializer.php
  plugin/path/Resources/translations/path.en.json
  plugin/path/Resources/translations/path.fr.json
Labels: no-squash

#5501 [BlogBundle][WikiBundle] Various fixes
  plugin/blog/Finder/PostFinder.php
  plugin/blog/Resources/modules/resources/blog/comment/store/reducer.js
  plugin/blog/Resources/modules/resources/blog/constants.js
  plugin/blog/Resources/modules/resources/blog/moderation/store/reducer.js
  plugin/blog/Resources/modules/resources/blog/post/components/post.jsx
  plugin/blog/Resources/modules/resources/blog/post/components/posts.jsx
  plugin/blog/Resources/modules/resources/blog/toolbar/components/tags.jsx
  plugin/blog/Resources/modules/resources/blog/utils.js
  plugin/blog/Serializer/BlogOptionsSerializer.php
  plugin/wiki/Listener/Resource/WikiListener.php
  plugin/wiki/Resources/modules/resources/wiki/components/resource.jsx
  plugin/wiki/Resources/modules/resources/wiki/constants.js
  plugin/wiki/Resources/modules/resources/wiki/history/components/history.jsx
  plugin/wiki/Serializer/WikiSerializer.php
Labels: BlogBundle, WikiBundle

#5521 Fixes ClacoForm serialization
  plugin/claco-form/Entity/ClacoForm.php
Labels: clacoForm

#5539 Multiple UI fixes
  main/app/Resources/modules/content/search/components/search.jsx
  main/core/Resources/modules/resource/actions/move.js
  main/core/Resources/modules/resource/explorer/store/actions.js
  plugin/blog/Controller/WidgetController.php
  plugin/rss/Resources/modules/resources/rss-feed/containers/resource.jsx
  plugin/rss/Resources/translations/rss.en.json
  plugin/rss/Resources/translations/rss.fr.json
  plugin/slideshow/Resources/modules/resources/slideshow/components/resource.jsx
  plugin/slideshow/Resources/modules/resources/slideshow/player/components/overview.jsx
  plugin/slideshow/Resources/modules/resources/slideshow/player/components/player.jsx
  plugin/slideshow/Resources/translations/slideshow.en.json
  plugin/slideshow/Resources/translations/slideshow.fr.json
  plugin/tag/Resources/modules/data/types/tag/components/filter.jsx
Labels: no-squash

#5552 [TeamBundle] Fixes number of members in a team
  plugin/team/Finder/TeamFinder.php
  plugin/team/Listener/TeamListener.php
  plugin/team/Resources/modules/tools/team/store/actions.js
  plugin/team/Serializer/TeamSerializer.php
Labels: TeamBundle

#5554 [AgendaBundle] Fixes translations in day view
  plugin/agenda/Resources/modules/tools/agenda/components/tool.jsx
Labels: AgendaBundle

#5559 [ScormBundle] Hides status message for API calls
  plugin/scorm/Resources/modules/resources/scorm/player/actions.js
Labels: ScormBundle

#5566 [ClcaoForm] Fixes relative URL in notifications
  plugin/claco-form/Manager/ClacoFormManager.php
Labels: clacoForm

#5565 [DropZoneBundle] Multiple fixes
  plugin/drop-zone/Resources/modules/resources/dropzone/components/documents.jsx
  plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/correction-form.jsx
  plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/modal/correction-modal.jsx
  plugin/drop-zone/Resources/modules/resources/dropzone/editor/components/editor.jsx
Labels: EvaluationBundle
